// Generated by CoffeeScript 1.9.2
var aesDecrypt, aesEncrypt, crypto, diaryDecrypt, diaryEncrypt, encryptUtil, sha1Hash;

crypto = require('crypto');

aesEncrypt = function(data, secretKey) {
  var cipher;
  cipher = crypto.createCipher('aes-128-ecb', secretKey);
  return cipher.update(data, 'utf8', 'hex') + cipher.final('hex');
};

aesDecrypt = function(data, secretKey) {
  var cipher;
  cipher = crypto.createDecipher('aes-128-ecb', secretKey);
  return cipher.update(data, 'hex', 'utf8') + cipher.final('utf8');
};

diaryEncrypt = function(data, secretKey) {
  var buf;
  buf = new Buffer(data, 'utf-8').toString('base64');
  return aesEncrypt(buf, secretKey);
};

diaryDecrypt = function(data, secretKey) {
  var base64Data;
  base64Data = aesDecrypt(data, secretKey);
  return new Buffer(base64Data, 'base64').toString('utf-8');
};

sha1Hash = function(clearString) {
  var sha1;
  sha1 = crypto.createHash('sha1');
  sha1.update(clearString);
  return sha1.digest('hex');
};

encryptUtil = {
  sha1Hash: sha1Hash,
  diaryEncrypt: diaryEncrypt,
  diaryDecrypt: diaryDecrypt
};

module.exports = encryptUtil;
