// Generated by CoffeeScript 1.9.2
var aesDecrypt, aesEncrypt, crypto, encryptUtil, sha1Hash;

crypto = require('crypto');

aesEncrypt = function(data, secretKey) {
  var cipher;
  cipher = crypto.createCipher('aes-128-ecb', secretKey);
  return cipher.update(data, 'utf8', 'hex') + cipher.final('hex');
};

aesDecrypt = function(data, secretKey) {
  var cipher;
  cipher = crypto.createDecipher('aes-128-ecb', secretKey);
  return cipher.update(data, 'hex', 'utf8') + cipher.final('utf8');
};

sha1Hash = function(clearString) {
  var sha1;
  sha1 = crypto.createHash('sha1');
  sha1.update(clearString);
  return sha1.digest('hex');
};

encryptUtil = {
  aesEncrypt: aesEncrypt,
  aesDecrypt: aesDecrypt,
  sha1Hash: sha1Hash
};

module.exports = encryptUtil;
