// Generated by CoffeeScript 1.9.2
var oceanUtil, showErrorNoticeWindow, showInfoNoticeWindow, showSuccessNoticeWindow, showWarningNoticeWindow;

showInfoNoticeWindow = function(noticeMessage, timeout) {
  return alert(noticeMessage);
};

showWarningNoticeWindow = function(noticeMessage) {
  return alert(noticeMessage);
};

showErrorNoticeWindow = function(noticeMessage) {
  return alert(noticeMessage);
};

showSuccessNoticeWindow = function(noticeMessage) {
  return alert(noticeMessage);
};

oceanUtil = {
  showInfoNoticeWindow: showInfoNoticeWindow,
  showWarningNoticeWindow: showWarningNoticeWindow,
  showErrorNoticeWindow: showErrorNoticeWindow,
  showSuccessNoticeWindow: showSuccessNoticeWindow
};

module.exports = oceanUtil;
