// Generated by CoffeeScript 1.9.2
var ForgetVue, config;

config = require('../config');

ForgetVue = require('./../vue/forget_vue');

module.exports = function() {
  return new ForgetVue({
    el: config.domIds.main
  });
};
