// Generated by CoffeeScript 1.9.2
var MainVue, config;

config = require('../config');

MainVue = require('./../vue/main_vue');

module.exports = function() {
  if (!window.oceanContext.userInfo.login) {
    window.location = config.siteAddress + '/#/login';
    return;
  }
  return new MainVue({
    el: config.domIds.main
  });
};
