// Generated by CoffeeScript 1.9.2
var ReadVue, config, exchangeService;

config = require('../config');

ReadVue = require('./../vue/read_vue');

exchangeService = require('./../service/exchange_service');

module.exports = function() {
  var criteria, rowDes;
  if (!window.oceanContext.userInfo.login) {
    window.location = config.siteAddress + '/#/login';
    return;
  }
  criteria = {
    createTime: {
      $lte: new Date().getTime()
    }
  };
  rowDes = {
    limit: 1,
    sort: {
      createTime: -1
    }
  };
  return exchangeService.queryDiary(criteria, null, rowDes, function(err, records) {
    var diary;
    if ((records != null) && (records[0] != null)) {
      diary = records[0];
      window.recentDiaryDate = diary.date;
      diary.pass = null;
    } else {
      diary = {
        _id: null,
        date: null,
        content: '',
        pass: null,
        passCheck: null
      };
    }
    return new ReadVue({
      el: config.domIds.main,
      data: diary
    });
  });
};
