// Generated by CoffeeScript 1.9.2
var ResetPassVue, config;

config = require('../config');

ResetPassVue = require('./../vue/reset_vue');

module.exports = function(resetToken) {
  return new ResetPassVue({
    el: config.domIds.main,
    data: {
      resetToken: resetToken
    }
  });
};
