// Generated by CoffeeScript 1.9.2
var WriteVue, _, config, dateFormat, exchangeService;

dateFormat = require('dateformat');

_ = require('underscore');

config = require('../config');

exchangeService = require('../service/exchange_service');

WriteVue = require('./../vue/write_vue');

module.exports = function() {
  var criteria, today;
  if (!window.oceanContext.userInfo.login) {
    window.location = config.siteAddress + '/#/login';
    return;
  }
  today = dateFormat(new Date(), 'yyyy-mm-dd');
  criteria = {
    date: today
  };
  return exchangeService.queryDiary(criteria, null, null, function(err, records) {
    var diary;
    if ((records != null) && (records[0] != null)) {
      diary = records[0];
      diary.pass = null;
    } else {
      diary = {
        _id: null,
        date: today,
        content: '',
        pass: null,
        passCheck: null
      };
    }
    return new WriteVue({
      el: config.domIds.main,
      data: diary
    });
  });
};
