// Generated by CoffeeScript 1.9.2
var $, ForgetVue, Vue, config, encryptUtil, exchangeService, myutils, pageService;

Vue = require('vue');

$ = window.$;

config = require('../config');

exchangeService = require('./../service/exchange_service');

pageService = require('./../service/page_service');

myutils = require('./../util/myutils');

encryptUtil = require('./../util/encrypt_util');

ForgetVue = Vue.extend({
  template: require('../template/forget.html'),
  ready: function() {
    $("#forget_div").css('padding-top', window.innerHeight * 0.3);
    return $(window).on('resize', function() {
      return $("#forget_div").css('padding-top', window.innerHeight * 0.3);
    });
  },
  methods: {
    removeError: function() {
      return $("#form_email").removeClass("has-error");
    },
    forget: function() {
      var user;
      if (!this.valid()) {
        return;
      }
      $("#icon_doing").removeClass("hidden");
      user = {
        accountName: this.$data.email
      };
      return exchangeService.forgetPassword(user, (function(_this) {
        return function(err) {
          $("#icon_doing").addClass("hidden");
          if ((err != null)) {
            return _this.$set('message', err.errorMessage);
          } else {
            return _this.$set('message', 'Reset confirm email already send to your email address!<br> 重置密码邮件已经发至您的邮箱！');
          }
        };
      })(this));
    },
    valid: function() {
      var emailReg, isValid;
      isValid = true;
      emailReg = /\w+((-\w+)|(\.\w+))*\@[A-Za-z0-9]+((\.|-)[A-Za-z0-9]+)*\.[A-Za-z0-9]+$/;
      if ((this.$data.email == null) || this.$data.email === '') {
        $("#form_email").addClass("has-error");
        isValid = false;
      } else if (!emailReg.test(this.$data.email)) {
        $("#form_email").addClass("has-error");
        isValid = false;
      }
      return isValid;
    }
  }
});

module.exports = ForgetVue;
