// Generated by CoffeeScript 1.9.2
var $, MainVue, Vue, config, exchangeService, myutils, pageService;

Vue = require('vue');

$ = window.$;

exchangeService = require('./../service/exchange_service');

pageService = require('./../service/page_service');

myutils = require('./../util/myutils');

config = require('./../config');

MainVue = Vue.extend({
  template: require('../template/main.html'),
  beforeCompile: function() {},
  ready: function() {},
  methods: {
    logout: function() {
      localStorage.removeItem('oceanContext');
      window.oceanContext = null;
      return window.location = config.siteAddress;
    }
  }
});

module.exports = MainVue;
