// Generated by CoffeeScript 1.9.2
var $, SignUpVue, Vue, config, encryptUtil, exchangeService, myutils, pageService;

Vue = require('vue');

$ = window.$;

config = require('../config');

exchangeService = require('./../service/exchange_service');

pageService = require('./../service/page_service');

myutils = require('./../util/myutils');

encryptUtil = require('./../util/encrypt_util');

SignUpVue = Vue.extend({
  template: require('../template/signup.html'),
  methods: {
    signUp: function() {
      var user;
      if (this.$data.password !== this.$data.passwordRepeat) {
        alert('Two password not match!');
        return;
      }
      user = {
        email: this.$data.email,
        accountName: this.$data.email,
        displayName: this.$data.email,
        password: encryptUtil.sha1Hash(this.$data.password),
        remember: true
      };
      return exchangeService.registerAccount(user, function(err) {
        if ((err != null)) {
          return alert(err.errorMessage);
        } else {
          return window.location = config.siteAddress + '/#/login';
        }
      });
    }
  }
});

module.exports = SignUpVue;
