// Generated by CoffeeScript 1.9.2
var Vue, WriteVue, config, dateFormat, encryptUtil, exchangeService, myutils;

Vue = require('vue');

exchangeService = require('./../service/exchange_service');

myutils = require('./../util/myutils');

encryptUtil = require('./../util/encrypt_util');

config = require('./../config');

dateFormat = require('dateformat');

WriteVue = Vue.extend({
  template: require('../template/write.html'),
  ready: function() {
    $("#diary_content textarea").focus();
    $('#lock_modal').on('shown.bs.modal', function() {
      return $('#modal_pass_input').focus();
    });
    $("#modal_pass_input").keydown((function(_this) {
      return function(e) {
        var key;
        key = e.which;
        if (key === 13) {
          if ($("#do_open_locked_diary:visible").size() > 0) {
            return _this.openLockedDiary();
          } else if ($("#do_lock_diary:visible").size() > 0) {
            return _this.lockDiary();
          }
        }
      };
    })(this));
    $("#diary_content").keydown((function(_this) {
      return function(e) {
        if ((event.ctrlKey || event.metaKey) && event.which === 83) {
          _this.save();
          event.preventDefault();
          return false;
        }
      };
    })(this));
    if ((this.$data.passCheck != null) && this.$data.passCheck !== '') {
      $("#diary_content").addClass('hidden');
      $("#diary_content_locked").removeClass('hidden');
      $("#icon_locked").addClass('hidden');
      $("#icon_openlock").removeClass('hidden');
      $("#icon_unlocked").addClass('hidden');
      $("#icon_do_save").addClass('hidden');
      $("#icon_do_save_disable").removeClass('hidden');
      $("#do_lock_diary").addClass('hidden');
      $("#do_open_locked_diary").removeClass('hidden');
    } else {
      $("#diary_content").removeClass('hidden');
      $("#diary_content_locked").addClass('hidden');
      $("#icon_locked").addClass('hidden');
      $("#icon_openlock").addClass('hidden');
      $("#icon_unlocked").removeClass('hidden');
      $("#icon_do_save").removeClass('hidden');
      $("#icon_do_save_disable").addClass('hidden');
      $("#do_lock_diary").removeClass('hidden');
      $("#do_open_locked_diary").addClass('hidden');
    }
    window.setInterval(this.save, 60 * 1000);
    if ((this.$data.passCheck != null) && this.$data.passCheck !== '') {
      return $('#lock_modal').modal('show');
    }
  },
  methods: {
    save: function() {
      var diary;
      if ((this.$data.content == null) || this.$data.content === '' || this.$data.content === this.$data.savedContent) {
        return;
      }
      if ((this.$data.pass == null) && (this.$data.passCheck != null)) {
        return;
      }
      if ((this.$data.passCheck != null) && this.$data.passCheck !== '') {
        diary = {
          date: this.$data.date,
          content: encryptUtil.aesEncrypt(this.$data.content, this.$data.pass),
          passCheck: this.$data.passCheck
        };
      } else {
        diary = {
          date: this.$data.date,
          content: this.$data.content,
          passCheck: null
        };
      }
      if ((this.$data._id != null)) {
        diary._id = this.$data._id;
      }
      $("#icon_saving").removeClass('hidden');
      return exchangeService.saveDiary(diary._id, diary, (function(_this) {
        return function(err, record) {
          $("#icon_saving").addClass('hidden');
          if ((err != null)) {
            return alert(err.errorMessage);
          } else {
            _this.$data._id = record._id;
            _this.$data.savedContent = _this.$data.content;
            return _this.$data.$set('updateTime', record.updateTime);
          }
        };
      })(this));
    },
    lockDiary: function() {
      if ((this.$data.pass == null) || this.$data.pass === '') {
        return;
      }
      this.$data.passCheck = encryptUtil.sha1Hash(this.$data.pass);
      $('#lock_modal').modal('hide');
      $("#do_lock_diary").addClass('hidden');
      $("#do_open_locked_diary").addClass('hidden');
      $("#icon_openlock").addClass('hidden');
      $("#icon_locked").removeClass('hidden');
      $("#icon_unlocked").addClass('hidden');
      return $("#diary_content textarea").focus();
    },
    openLockedDiary: function() {
      if (this.$data.passCheck !== encryptUtil.sha1Hash(this.$data.pass)) {
        return alert('Not Right');
      } else {
        this.$data.content = encryptUtil.aesDecrypt(this.$data.content, this.$data.pass);
        $('#lock_modal').modal('hide');
        $("#diary_content").removeClass('hidden');
        $("#diary_content_locked").addClass('hidden');
        $("#do_lock_diary").addClass('hidden');
        $("#do_open_locked_diary").addClass('hidden');
        $("#icon_do_save").removeClass('hidden');
        $("#icon_do_save_disable").addClass('hidden');
        $("#icon_openlock").addClass('hidden');
        $("#icon_locked").removeClass('hidden');
        $("#icon_unlocked").addClass('hidden');
        return $("#diary_content textarea").focus();
      }
    }
  }
});

module.exports = WriteVue;
