// Generated by CoffeeScript 1.9.2
var config;

config = {};

config.appKey = 'diary';

config.siteAddress = 'http://diary.lonetime.com';

config.apiResources = {
  userRegister: function() {
    return window.oceanContext.backServices.user.api + '/register';
  },
  userLogin: function() {
    return window.oceanContext.backServices.user.api + '/login';
  },
  userUpdate: function() {
    return window.oceanContext.backServices.user.api + '/update';
  },
  forgetPassword: function() {
    return window.oceanContext.backServices.user.api + '/forget_password';
  },
  resetPassword: function() {
    return window.oceanContext.backServices.user.api + '/reset_password';
  },
  getAnonymousOceanContext: function() {
    return 'https://api.oceanclouds.com/v1.0/public/ocean_context/' + config.appKey;
  },
  getEndUserOceanContext: function() {
    return 'https://api.oceanclouds.com/v1.0/end/ocean_context/' + config.appKey;
  },
  diaryCrudAddress: function(_id, isQuery) {
    if ((_id != null)) {
      return window.oceanContext.backServices.crud.api + '/' + config.appKey + '/diary/' + _id;
    } else if (isQuery) {
      return window.oceanContext.backServices.crud.api + '/' + config.appKey + '/diary/find/query';
    } else {
      return window.oceanContext.backServices.crud.api + '/' + config.appKey + '/diary';
    }
  }
};

config.domIds = {
  main: '#main'
};

module.exports = config;
