// Generated by CoffeeScript 1.9.2
var forget, login, main, read, reset, routes, signup, write;

main = require('./route/main');

login = require('./route/login');

signup = require('./route/signup');

reset = require('./route/reset_pass');

forget = require('./route/forget');

write = require('./route/write');

read = require('./route/read');

routes = {
  '/main': function() {
    return main();
  },
  '/login': function() {
    return login();
  },
  '/signup': function() {
    return signup();
  },
  '/write': function() {
    return write();
  },
  '/read': function() {
    return read();
  },
  '/forget': function() {
    return forget();
  },
  '/reset/:token': function(token) {
    return reset(token);
  }
};

module.exports = routes;
