// Generated by CoffeeScript 1.9.2
var login, main, read, routes, signup, write;

main = require('./route/main');

login = require('./route/login');

signup = require('./route/signup');

write = require('./route/write');

read = require('./route/read');

routes = {
  '/main': function() {
    return main();
  },
  '/login': function() {
    return login();
  },
  '/signup': function() {
    return signup();
  },
  '/write': function() {
    return write();
  },
  '/read': function() {
    return read();
  }
};

module.exports = routes;
